README.md, pyproject.toml, sydney/sydney.py
- Move cookie loading inside Sydney client.
- Add method to reset conversation.
=> Add method to reset conversation

README.md, pyproject.toml, sydney/sydney.py
- Add citations and raw response parameters
- Update usage example
- Improve docstrings
=> Add citations and raw response parameters

sydney/constants.py, sydney/enums.py, sydney/sydney.py, sydney/utils.py
- Add files for constants, enums and helper functions
=> Split code into multiple files

sydney/sydney.py
- Use flag to exit streaming loop
- Close websocket connection after every prompt
=> Close websocket connection after every prompt

README.md, pyproject.toml, sydney/sydney.py
- Fix reset conversation when new style is not provided
=> Fix reset conversation

README.md, pyproject.toml, sydney/constants.py
- Update user agent header version to latest Edge version
=> Update user agent header version

README.md, pyproject.toml, sydney/sydney.py
- Stream new tokens only in text mode
- Update usage example to showcase more client features
=> Stream new tokens only

sydney/sydney.py
=> Fix type hints

sydney/sydney.py
- Add optional Bing _U cookie parameter. If not provided, the `BING_U_COOKIE` environment variable is loaded instead. Default is None.
=> Add optional Bing _U cookie parameter

sydney/enums.py, sydney/sydney.py
- Make enum parameters case insensitive
- Capitalize enums
=> Make enum parameters case insensitive

README.md, pyproject.toml
- Improve README by providing an example CLI client and documenting all supported features with short examples
=> Improve feature documentation and examples

sydney/constants.py
- Update Edge user agent to latest version
=> Update user agent version

README.md, sydney/sydney.py
- Improve documentation.
- Make minor improvements in the code.
=> Improve documentation

sydney/exceptions.py, sydney/sydney.py
- Improve error handling with new exceptions: `NoConnectionException` and `NoResponseException`.
- Improve type hints to fix all `mypy` related errors.
=> Improve error handling and type hints

.github/workflows/test.yml, README.md, poetry.lock, pyproject.toml
- Add initial testing pipeline. Performs type checks with `mypy`.
=> Add test pipeline

README.md
- Add missing `await` keyword on usage examples.
=> Fix usage examples

README.md, pyproject.toml, sydney/constants.py
- Update User Agent to latest version.
=> Update User Agent

README.md, pyproject.toml, sydney/enums.py, sydney/sydney.py
- Update conversation style enums to match the updates options sets used by Bing Chat.
=> Update conversation style enums

README.md, pyproject.toml, sydney/sydney.py
- Fix issue where multiple responses can be streamed, if `raw` or `citations` are set to `True`.
=> Fix duplicate streaming responses

sydney/enums.py, sydney/exceptions.py, sydney/sydney.py
- Add exception and error handling to detect when client is getting throttled. Happens when more than 200 (subject to change) messages are sent in one day.
=> Add throttled message error handling

sydney/exceptions.py, sydney/sydney.py
- Raise exception if conversation limit is increased
- Keep current & max number of messages in conversation in Sydney client
=> Support raising exception on conversation limit

sydney/constants.py, sydney/sydney.py
- Fix minor typo in constant variable
=> Fix typo in constant

README.md, pyproject.toml, sydney/constants.py, sydney/sydney.py, tests/test_conversation.py
- Add new method for fetching all conversations for current client
- Add test for new method
=> Add get conversations method

sydney/constants.py, sydney/sydney.py
Here are the changes I made to get Sydney.py working for me, as discussed in #51.
=> Fix conversationSignature key error

README.md, pyproject.toml, sydney/sydney.py
- Make minor improvements to conversation signature handling by removing code that is not needed
- Format code
=> Make minor improvements to conversation signature handling

README.md, pyproject.toml, sydney/sydney.py
- Fix potential exception when fetching suggested responses
- Improve docstrings and README
=> Fix potential exception when fetching suggested responses

README.md, pyproject.toml, sydney/constants.py
- Fix create conversation URL by replacing the old one which is becoming inaccessible with an up to date URL that currently works
=> Fix create conversation URL

README.md
- Update cookie instructions due to breaking changes on Bing Chat that result in Captcha errors
=> Update cookie instructions

README.md, sydney/exceptions.py, sydney/sydney.py
- Remove generic exceptions and replace them with specific, custom exceptions
- Add exceptions section in README
=> Remove generic exceptions

README.md, sydney/sydney.py, tests/test_ask.py, tests/test_compose.py, tests/test_conversation.py
- Combine `_ask` and `_compose` methods into one to avoid duplicate code.
- Fix various bugs with handling response messages from Bing Chat.
- Expand testing coverage.
=> Refactor ask method and expand testing coverage

sydney/constants.py
- Expand chat headers by including additional fields, such as `Origin`
=> Expand chat headers

README.md, pyproject.toml, sydney/sydney.py
- Move code that builds attachment upload argument into separate method
=> Refactor attachment upload code

README.md, sydney/sydney.py
- Make usage of cookies optional
- Improve and update README
=> Make cookies optional

sydney/enums.py, sydney/sydney.py
- Fix conversation style usage by providing the correct value when uploading an image
- Improve compatibility of ask arguments
- Fix image upload blobId handling by omitting processedBlobId
=> Fix image upload blobID handling

README.md, pyproject.toml, sydney/sydney.py
- Add parameter to allow providing a web page as additional context.
- Update README
=> Add web context parameter on ask

README.md, pyproject.toml, sydney/sydney.py
- Fix handling of 'Searching the web' messages that would sometimes be returned when handling streaming responses.
=> Fix searching web message handling

README.md, pyproject.toml, sydney/enums.py, sydney/sydney.py
- Make arguments provided for `ask` and `compose` more consistent with that browser sends to Bing Chat
=> Fix discrepancies in request arguments

sydney/constants.py
- Update create conversation URL to be consistent with what is used on the main Bing Chat page
=> Update create conversation URL

tests/test_ask.py
- Improve testing by adding additional test cases and improving current tests
- Use image from repo to avoid relying on external pages
=> Add additional tests

README.md, pyproject.toml, sydney/exceptions.py, sydney/sydney.py
- Improve timeout error handling with custom exception
- Organize imports
=> Improve timeout error handling

.github/workflows/test.yml
- Run tests automatically every Friday to detect bugs and breaking changes in the API
=> Run tests weekly

README.md, pyproject.toml, sydney/enums.py, sydney/sydney.py
- Create helper enums to use and document options that are used for ask & compose requests
- Improve compatibility of options used for ask requests
=> Improve compatibility of ask arguments

README.md, pyproject.toml, sydney/constants.py, sydney/sydney.py, sydney/utils.py
- Replace _U cookie with all Bing cookies for better compatibility
- Fix issue where conversation ID would contain `BingProdUnAuthenticatedUsers` string instead of `BingProd`
=> Replace _U cookie with all Bing cookies

README.md, pyproject.toml, sydney/utils.py
- Fix cookie parsing so that it works when cookies are provided by extensions such as `Cookies-Editor`
=> Fix cookie parsing

README.md, pyproject.toml, sydney/sydney.py, sydney/utils.py, tests/test_ask.py
- Add support for attaching local images to prompts
- Improve testing
=> Add support for attaching local images to prompts

.github/workflows/test.yml, README.md, poetry.lock, pyproject.toml, sydney/constants.py, tests/test_ask.py
- Update bundle version
- Update user agent
- Update request headers
- Update request URLs
- Improve testing
=> Fix compatibility with Copilot API

.github/workflows/test.yml, sydney/constants.py, tests/test_ask.py, tests/test_conversation.py
- Improve tests
- Update user agent
- Remove Bing Chat references from tests
=> Improve tests

README.md, pyproject.toml, sydney/sydney.py
- Fix key error that happens when citations are enabled and `altText` is provided instead of `text`
- Format code to have longer line length
=> Fix key error

README.md, pyproject.toml, sydney/sydney.py
- Fix index to resolve additional key error
=> Fix second key error

sydney/constants.py, sydney/sydney.py
- Improve header compatibility
- Update bundle version
- Improve upload image compatibility
=> Improve headers compatibility

tests/test_ask.py
- Resolve test failures by improving testing
=> Improve testing

README.md, pyproject.toml, sydney/constants.py, sydney/sydney.py
- Update bundle version, headers and user agent
- Improve compatibility with Copilot API by updating the request parameters
=> Improve API compatibility

README.md, pyproject.toml, sydney/enums.py, sydney/sydney.py, tests/test_ask.py
- Add support for `travel`, `cooking` and `fitness` personas
- Add testing for the personas
- Update documentation with usage of the personas
=> Add support for personas

sydney/sydney.py
- Replace `getattr` with `enum[...]` for cleaner code
=> Do minor refactor

tests/test_ask.py
- Add testing for invalid parameters when creating a Sydney client
=> Add testing for invalid parameters

.github/workflows/test.yml, README.md, poetry.lock, pyproject.toml
- Remove black formatter from dev dependencies
=> Remove black formatter dependency

.pre-commit-config.yaml, poetry.lock, pyproject.toml
- Use pre-commit with useful options
=> Use pre-commit
